### ISSUE TITLE
intent to upgrade github3.py library

### ISSUE THREAD

**Issue by hwine** [mozilla/github-org-scripts#13]
The newer (1.0.0a2) develop branch versions of the [github3.py](https://github.com/sigmavirus24/github3.py.git) package have a number of nice additions to support the modern Organization features. 
However, there are a number of breaking changes that will require rework of some existing scripts.
Because of the compatibility issues, and that the upstream copy does not yet have a release date, I'll do this work on  a new branch, which will include the github3.py code as a [git subtree](https://medium.com/@porteneuve/mastering-git-subtrees-943d29a798ec#.pj31dd7ik) (manual method).

Any objections or concerns? Please post in this issue.

**Comment by hwine** [comment]
@fwenzel @groovecoder  as contributors to date, you likely care the most about this.

**Comment by groovecoder** [comment]
Sounds like a good approach to me. Godspeed.
