### ISSUE TITLE
Convert to MPL?

### ISSUE THREAD

**Issue by hwine** [mozilla/github-org-scripts#17]
Not sure if there's a reason early work in this repo was BSD. Would seem to make more sense to have under MPL.

@fwenzel do you know the original reason? Or have objection to switching?

**Comment by fwenzel** [comment]
Sorry for the delay answering this. The original reason was to use a permissive license so anyone can use it without needing to contribute back. Relicensing as MPL seems fine, or Apache, which I seem to recall is the "MIT-like" license Mozilla internally uses (basically: MPL if copyleft is desired, Apache if not).
