### ISSUE TITLE
LFS usage script

### ISSUE THREAD

**Issue by jgmize** [mozilla/github-org-scripts#22]
Description from @hwine via email: 

 - iterate over all repositories using api.github.com
  - for each repository, attempt to retrieve the raw .gitattributes file
    - if it does not exist, that repo does not have LFS
    - if it does exist, examine contents to see if LFS attributes are there (this is the part I don't have figured out, but appears to be well documented in the LFS project)
  - once it's known a given repo has LFS attributes:
     - clone the repo (a shallow clone may suffice)
     - execute git lfs ls-files <= gives counts & size

**Comment by hwine** [comment]
note: we're currently awaiting reporting from GitHub, so may not need to undertake this urgently.

**Comment by jgmize** [comment]
@mykmelez pointed out via email that repos with lfs in the .gitattributes file can be quickly identified by searching for [org:mozilla filename:.gitattributes lfs](https://github.com/search?utf8=%E2%9C%93&q=org%3Amozilla+filename%3A.gitattributes+lfs&type=Code&ref=searchresults), and since github will be providing reports I don't see any reason to leave this issue open.
